services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hw_db
    volumes:
      - "/home/HP/data-engineering-zoomcamp-2025/homework/first_homework/green_taxi_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - "pg-network"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home/HP/data-engineering-zoomcamp-2025/homework/first_homework/data_pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"
    networks:
      - "pg-network"
    
networks:
    pg-network:
